### ISSUE TITLE
Various small fixes

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/api-filestore#9]
As part of the change to the API test suite, I found a couple of small fixes that need to be applied to this connector. I'm more than happy to work on them, just keeping them here for reference:

- [x] The `update` method needs to return an object with a `matchedCount` property, not an array of documents (https://github.com/dadi/api-filestore/blob/master/lib/index.js#L339)

- [x] The `$push` keyword needs to be reinstated for History to work as expected

- [x] Remove config schema validation (https://github.com/dadi/api-filestore/blob/master/config.js#L39)
- [ ] The various operations need to return a rejected Promise if a connection with the database can't be established (i.e. `readyState` isn't `1`)

**Comment by jimlambie** [comment]
I agree with everything ❤️

**Comment by jimlambie** [comment]
With regard to the stripping out of internal properties, this part was supposed to instruct API how to handle the issue:

https://github.com/dadi/api-filestore/blob/master/lib/index.js#L56

However, I'm happy for them to be removed from the documents before returning.

**Comment by eduardoboucas** [comment]
Removed that item from the list, as it's now being handled by API in https://github.com/dadi/api/pull/369.

**Comment by eduardoboucas** [comment]
> The various operations need to return a rejected Promise if a connection with the database can't be established (i.e. readyState isn't 1)

Actually, I don't think we need this. We're talking about an in-memory database, so in theory the connection will always be available. We could have issues when trying to persist to disk, but that doesn't happen when the model methods are called, so a rejected Promise won't help us here.

Do you concur @jimlambie?

**Comment by eduardoboucas** [comment]
👴
